#!/usr/bin/env bash
set -euo pipefail

ZANO_SOURCE="${1:-${ZANO_SOURCE:-/home/jdawg/zano}}"
ZANO_BUILD="${2:-${ZANO_BUILD:-$ZANO_SOURCE/build}}"
P2POOL_SOURCE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT_DIR="$P2POOL_SOURCE/build-zano-oracle"

FLAGS_FILE="$(find "$ZANO_BUILD" -path '*/CMakeFiles/connectivity_tool.dir/flags.make' -print -quit 2>/dev/null || true)"
LINK_FILE="$(find "$ZANO_BUILD" -path '*/CMakeFiles/connectivity_tool.dir/link.txt' -print -quit 2>/dev/null || true)"

if [[ -z "$FLAGS_FILE" || -z "$LINK_FILE" ]]; then
    echo "error: could not find connectivity_tool build metadata under: $ZANO_BUILD" >&2
    echo "Build Zano first, or pass the correct Zano build directory as argument 2." >&2
    exit 1
fi

mkdir -p "$OUT_DIR"

# CMake's generated flags.make is shell-compatible for these assignments.
CXX_DEFINES=""
CXX_INCLUDES=""
CXX_FLAGS=""
# shellcheck disable=SC1090
source "$FLAGS_FILE"

CXX_BIN="$(awk '{print $1}' "$LINK_FILE")"
LINK_LINE="$(cat "$LINK_FILE")"

# Keep the exact library/linker tail used by Zano's connectivity_tool, but
# replace that target's object list and output path with our one object.
if [[ "$LINK_LINE" != *" -o connectivity_tool "* ]]; then
    echo "error: unexpected Zano connectivity_tool link command" >&2
    echo "$LINK_LINE" >&2
    exit 1
fi
LINK_TAIL="${LINK_LINE#* -o connectivity_tool }"

SRC="$P2POOL_SOURCE/tools/zano_header_oracle.cpp"
OBJ="$OUT_DIR/zano_header_oracle.o"
BIN="$OUT_DIR/zano-header-oracle"

# Word splitting is intentional: these variables are generated by CMake as
# compiler flag lists.
# shellcheck disable=SC2086
"$CXX_BIN" $CXX_DEFINES $CXX_INCLUDES $CXX_FLAGS \
    -I"$ZANO_SOURCE/src" \
    -c "$SRC" -o "$OBJ"

# The link tail contains Zano's exact static/shared dependency ordering.
# shellcheck disable=SC2086
"$CXX_BIN" "$OBJ" -o "$BIN" $LINK_TAIL

printf 'Built: %s\n' "$BIN"
